spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**  

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**  

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**  

        - id: register-service
          uri: lb://register-service
          predicates:
            - Path=/user/**  

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  boot:
    admin:
      client:
        url: http://localhost:9090
        instance:
          management-base-url: http://localhost:7000
        username: admin
        password: admin

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost





security:
  basic:
    enabled: false
    
management:
    security:
      enabled: false
      
server:
    port: 7000

    

